services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5555:5555" 
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://admin:secret@db:5432/ecommerce
      - TOKEN_SECRET=038ffdf1548e71e7340dbf5d33cc6e811bace472895fdda7c226a91c27e65425437a7f840ddbd5ede8d642dab4f94c45e7adb3fa2ee8bb214d36e8846ce1b9aa
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pnpm dev"
    
  db:
    image: postgres:15
    container_name: postgres-db-lt
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ecommerce"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data: