- name: Install Docker, Docker Compose, and Deploy Jenkins
  hosts: 165.154.203.72
  become: true
  vars:
    docker_compose_version: "1.29.2"
    jenkins_container_name: "jenkins"
    jenkins_home: "/var/jenkins_home"
    jenkins_port: 8080

  tasks:
    # ✅ Ensure Jenkins home directory exists and has correct permissions
    - name: Create Jenkins home directory
      file:
        path: "{{ jenkins_home }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0755"

    - name: Create Jenkins secrets directory
      file:
        path: "{{ jenkins_home }}/secrets"
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0755"

    - name: Fix ownership of Jenkins home directory
      command: "chown -R 1000:1000 {{ jenkins_home }}"

    # ✅ Deploy Jenkins container
    - name: Run Jenkins container
      docker_container:
        name: "{{ jenkins_container_name }}"
        image: "jenkins/jenkins:lts"
        state: started
        restart_policy: always
        ports:
          - "{{ jenkins_port }}:8080"
        volumes:
          - "{{ jenkins_home }}:/var/jenkins_home"
          - "/var/run/docker.sock:/var/run/docker.sock"
        user: "1000" # Run Jenkins as user 1000

    # ✅ Wait for Jenkins to initialize properly
    - name: Wait for Jenkins to create the admin password file
      shell: "while [ ! -f {{ jenkins_home }}/secrets/initialAdminPassword ]; do sleep 10; done"
      args:
        executable: /bin/bash
      register: wait_result
      changed_when: false
      timeout: 600 # Increase timeout to 10 minutes

    # ✅ Retrieve and print Jenkins admin password
    - name: Get Jenkins admin password
      command: "cat {{ jenkins_home }}/secrets/initialAdminPassword"
      register: jenkins_password
      changed_when: false

    - debug:
        msg: "Jenkins Admin Password: {{ jenkins_password.stdout }}"
